name: dirasiq
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+2

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.7.0
  intl: ^0.20.2
  get: ^4.6.6
  google_sign_in: ^6.2.2
  sign_in_with_apple: ^6.1.0
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.3.3
  geolocator: ^12.0.0
  video_player: ^2.9.2
  better_player_plus: ^1.1.2
  flutter_localizations: #  مهم عشان DatePicker واللغات
    sdk: flutter
  onesignal_flutter: ^5.1.4
  app_badge_plus:
  permission_handler: ^11.3.1
  mobile_scanner: ^7.1.3
  url_launcher: ^6.3.0
  image_picker: ^1.1.2
  file_picker: ^8.0.3
  fl_chart: ^0.68.0
  table_calendar: ^3.0.10
  google_fonts: ^6.2.1
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.1
flutter:
  uses-material-design: true

  assets:
    - assets/

# Configure launcher icons
flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/logo.png
  min_sdk_android: 21
  remove_alpha_ios: true

# Configure native splash
flutter_native_splash:
  android: true
  ios: true
  web: false
  color: "#FFFFFF"
  color_dark: "#121212"
  image: assets/logo.png
  image_dark: assets/logo.png
  android_12:
    image: assets/logo.png
    image_dark: assets/logo.png
    icon_background_color: "#FFFFFF"
    icon_background_color_dark: "#121212"
